# backend/services/llm_service.py
from tenacity import retry, wait_random_exponential, stop_after_attempt
from openai import AzureOpenAI, RateLimitError, APITimeoutError
from app.core.config import settings


class LLMService:
    def __init__(self):
        self.client = AzureOpenAI(
            api_key=settings.AZURE_OPENAI_API_KEY,
            azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
            api_version=settings.AZURE_OPENAI_API_VERSION,
        )

    @retry(
        wait=wait_random_exponential(min=1, max=10),
        stop=stop_after_attempt(5),
        retry=(RateLimitError, APITimeoutError),
    )
    async def nl_to_sql(self, question: str) -> str:
        """
        Convert natural language question into SAFE SQL SELECT
        """
        prompt = f"""
You are an expert SAP SQL assistant.

ONLY return a SINGLE SQLite SELECT statement.
DO NOT use INSERT, UPDATE, DELETE.
DO NOT use semicolons.
DO NOT explain anything.

Available tables:
materials(material_id, material_name, material_type, base_unit, material_group, created_date)
customers(customer_id, customer_name, country, city, credit_limit, customer_group)
sales_orders(order_id, customer_id, order_date, total_amount, currency, status, sales_org)
sales_order_items(order_id, item_number, material_id, quantity, unit_price, net_value, delivery_date)
inventory(material_id, plant, storage_location, quantity, unit, last_updated)
purchase_orders(po_number, vendor_id, po_date, total_amount, currency, status)

Question:
{question}
"""
        response = self.client.chat.completions.create(
            model=settings.AZURE_OPENAI_DEPLOYMENT_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=256,
        )

        sql = response.choices[0].message.content.strip()
        if not sql.lower().startswith("select") or ";" in sql:
            raise ValueError("Unsafe SQL generated by LLM")

        return sql

    @retry(
        wait=wait_random_exponential(min=1, max=10),
        stop=stop_after_attempt(5),
        retry=(RateLimitError, APITimeoutError),
    )
    async def summarize_results(self, question: str, columns, rows) -> str:
        prompt = f"""
User question:
{question}

SQL result columns:
{columns}

SQL result rows:
{rows[:10]}

Provide a short, clear, business-friendly answer.
"""
        response = self.client.chat.completions.create(
            model=settings.AZURE_OPENAI_DEPLOYMENT_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=200,
        )
        return response.choices[0].message.content.strip()
